# Generated by Django 4.2.2 on 2023-07-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("electoral", "0005_reps_2022_reps_2016_reps_2010"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pres_2010",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Benigno_Aquino", models.IntegerField()),
                ("Joseph_Estrada", models.IntegerField()),
                ("Manny_Villar", models.IntegerField()),
                ("Gilbert_Teodoro", models.IntegerField()),
                ("Eddie_Villanueva", models.IntegerField()),
                ("Dick_Gordon", models.IntegerField()),
                ("Nicanor_Perlas", models.IntegerField()),
                ("Jamby_Madrigal", models.IntegerField()),
                ("John_delosReyes", models.IntegerField()),
                (
                    "province_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electoral.province",
                    ),
                ),
            ],
        ),
    ]
